//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Метаданные связи EDM

[assembly: EdmRelationshipAttribute("Modeltest", "UserAccountsPersonality", "UserAccount", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Report.Test.UserAccount), "sPersonality", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Report.Test.sPersonality), true)]

#endregion

namespace Report.Test
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class rIrCampusStudyEntities : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект rIrCampusStudyEntities, используя строку соединения из раздела "rIrCampusStudyEntities" файла конфигурации приложения.
        /// </summary>
        public rIrCampusStudyEntities() : base("name=rIrCampusStudyEntities", "rIrCampusStudyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта rIrCampusStudyEntities.
        /// </summary>
        public rIrCampusStudyEntities(string connectionString) : base(connectionString, "rIrCampusStudyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта rIrCampusStudyEntities.
        /// </summary>
        public rIrCampusStudyEntities(EntityConnection connection) : base(connection, "rIrCampusStudyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<sPersonality> sPersonality
        {
            get
            {
                if ((_sPersonality == null))
                {
                    _sPersonality = base.CreateObjectSet<sPersonality>("sPersonality");
                }
                return _sPersonality;
            }
        }
        private ObjectSet<sPersonality> _sPersonality;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<UserAccount> UserAccount
        {
            get
            {
                if ((_UserAccount == null))
                {
                    _UserAccount = base.CreateObjectSet<UserAccount>("UserAccount");
                }
                return _UserAccount;
            }
        }
        private ObjectSet<UserAccount> _UserAccount;

        #endregion
        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet sPersonality. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTosPersonality(sPersonality sPersonality)
        {
            base.AddObject("sPersonality", sPersonality);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet UserAccount. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToUserAccount(UserAccount userAccount)
        {
            base.AddObject("UserAccount", userAccount);
        }

        #endregion
    }
    

    #endregion
    
    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modeltest", Name="sPersonality")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sPersonality : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта sPersonality.
        /// </summary>
        /// <param name="id">Исходное значение свойства Id.</param>
        /// <param name="sTUDENT_ID">Исходное значение свойства STUDENT_ID.</param>
        /// <param name="lAST_NAME">Исходное значение свойства LAST_NAME.</param>
        /// <param name="fIRST_NAME">Исходное значение свойства FIRST_NAME.</param>
        /// <param name="dATE_OF_BIRTH">Исходное значение свойства DATE_OF_BIRTH.</param>
        /// <param name="pERSON_DOCUMENT_NUMBER">Исходное значение свойства PERSON_DOCUMENT_NUMBER.</param>
        /// <param name="sEX_NAME">Исходное значение свойства SEX_NAME.</param>
        /// <param name="sTUDY_GROUP_NAME">Исходное значение свойства STUDY_GROUP_NAME.</param>
        /// <param name="cOURSE_ID">Исходное значение свойства COURSE_ID.</param>
        /// <param name="iS_CONTRACT">Исходное значение свойства IS_CONTRACT.</param>
        /// <param name="sPECIALITY_CODE">Исходное значение свойства SPECIALITY_CODE.</param>
        public static sPersonality CreatesPersonality(global::System.Int32 id, global::System.String sTUDENT_ID, global::System.String lAST_NAME, global::System.String fIRST_NAME, global::System.DateTime dATE_OF_BIRTH, global::System.String pERSON_DOCUMENT_NUMBER, global::System.String sEX_NAME, global::System.String sTUDY_GROUP_NAME, global::System.Int32 cOURSE_ID, global::System.String iS_CONTRACT, global::System.String sPECIALITY_CODE)
        {
            sPersonality sPersonality = new sPersonality();
            sPersonality.Id = id;
            sPersonality.STUDENT_ID = sTUDENT_ID;
            sPersonality.LAST_NAME = lAST_NAME;
            sPersonality.FIRST_NAME = fIRST_NAME;
            sPersonality.DATE_OF_BIRTH = dATE_OF_BIRTH;
            sPersonality.PERSON_DOCUMENT_NUMBER = pERSON_DOCUMENT_NUMBER;
            sPersonality.SEX_NAME = sEX_NAME;
            sPersonality.STUDY_GROUP_NAME = sTUDY_GROUP_NAME;
            sPersonality.COURSE_ID = cOURSE_ID;
            sPersonality.IS_CONTRACT = iS_CONTRACT;
            sPersonality.SPECIALITY_CODE = sPECIALITY_CODE;
            return sPersonality;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String STUDENT_ID
        {
            get
            {
                return _STUDENT_ID;
            }
            set
            {
                OnSTUDENT_IDChanging(value);
                ReportPropertyChanging("STUDENT_ID");
                _STUDENT_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("STUDENT_ID");
                OnSTUDENT_IDChanged();
            }
        }
        private global::System.String _STUDENT_ID;
        partial void OnSTUDENT_IDChanging(global::System.String value);
        partial void OnSTUDENT_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LAST_NAME
        {
            get
            {
                return _LAST_NAME;
            }
            set
            {
                OnLAST_NAMEChanging(value);
                ReportPropertyChanging("LAST_NAME");
                _LAST_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LAST_NAME");
                OnLAST_NAMEChanged();
            }
        }
        private global::System.String _LAST_NAME;
        partial void OnLAST_NAMEChanging(global::System.String value);
        partial void OnLAST_NAMEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FIRST_NAME
        {
            get
            {
                return _FIRST_NAME;
            }
            set
            {
                OnFIRST_NAMEChanging(value);
                ReportPropertyChanging("FIRST_NAME");
                _FIRST_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FIRST_NAME");
                OnFIRST_NAMEChanged();
            }
        }
        private global::System.String _FIRST_NAME;
        partial void OnFIRST_NAMEChanging(global::System.String value);
        partial void OnFIRST_NAMEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MIDDLE_NAME
        {
            get
            {
                return _MIDDLE_NAME;
            }
            set
            {
                OnMIDDLE_NAMEChanging(value);
                ReportPropertyChanging("MIDDLE_NAME");
                _MIDDLE_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MIDDLE_NAME");
                OnMIDDLE_NAMEChanged();
            }
        }
        private global::System.String _MIDDLE_NAME;
        partial void OnMIDDLE_NAMEChanging(global::System.String value);
        partial void OnMIDDLE_NAMEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATE_OF_BIRTH
        {
            get
            {
                return _DATE_OF_BIRTH;
            }
            set
            {
                OnDATE_OF_BIRTHChanging(value);
                ReportPropertyChanging("DATE_OF_BIRTH");
                _DATE_OF_BIRTH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE_OF_BIRTH");
                OnDATE_OF_BIRTHChanged();
            }
        }
        private global::System.DateTime _DATE_OF_BIRTH;
        partial void OnDATE_OF_BIRTHChanging(global::System.DateTime value);
        partial void OnDATE_OF_BIRTHChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IPN
        {
            get
            {
                return _IPN;
            }
            set
            {
                OnIPNChanging(value);
                ReportPropertyChanging("IPN");
                _IPN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IPN");
                OnIPNChanged();
            }
        }
        private global::System.String _IPN;
        partial void OnIPNChanging(global::System.String value);
        partial void OnIPNChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PERSON_DOCUMENT_SERIES
        {
            get
            {
                return _PERSON_DOCUMENT_SERIES;
            }
            set
            {
                OnPERSON_DOCUMENT_SERIESChanging(value);
                ReportPropertyChanging("PERSON_DOCUMENT_SERIES");
                _PERSON_DOCUMENT_SERIES = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PERSON_DOCUMENT_SERIES");
                OnPERSON_DOCUMENT_SERIESChanged();
            }
        }
        private global::System.String _PERSON_DOCUMENT_SERIES;
        partial void OnPERSON_DOCUMENT_SERIESChanging(global::System.String value);
        partial void OnPERSON_DOCUMENT_SERIESChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PERSON_DOCUMENT_DATE
        {
            get
            {
                return _PERSON_DOCUMENT_DATE;
            }
            set
            {
                OnPERSON_DOCUMENT_DATEChanging(value);
                ReportPropertyChanging("PERSON_DOCUMENT_DATE");
                _PERSON_DOCUMENT_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PERSON_DOCUMENT_DATE");
                OnPERSON_DOCUMENT_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _PERSON_DOCUMENT_DATE;
        partial void OnPERSON_DOCUMENT_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnPERSON_DOCUMENT_DATEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PERSON_DOCUMENT_NUMBER
        {
            get
            {
                return _PERSON_DOCUMENT_NUMBER;
            }
            set
            {
                OnPERSON_DOCUMENT_NUMBERChanging(value);
                ReportPropertyChanging("PERSON_DOCUMENT_NUMBER");
                _PERSON_DOCUMENT_NUMBER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PERSON_DOCUMENT_NUMBER");
                OnPERSON_DOCUMENT_NUMBERChanged();
            }
        }
        private global::System.String _PERSON_DOCUMENT_NUMBER;
        partial void OnPERSON_DOCUMENT_NUMBERChanging(global::System.String value);
        partial void OnPERSON_DOCUMENT_NUMBERChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PERSON_DOCUMENT_ORGAN
        {
            get
            {
                return _PERSON_DOCUMENT_ORGAN;
            }
            set
            {
                OnPERSON_DOCUMENT_ORGANChanging(value);
                ReportPropertyChanging("PERSON_DOCUMENT_ORGAN");
                _PERSON_DOCUMENT_ORGAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PERSON_DOCUMENT_ORGAN");
                OnPERSON_DOCUMENT_ORGANChanged();
            }
        }
        private global::System.String _PERSON_DOCUMENT_ORGAN;
        partial void OnPERSON_DOCUMENT_ORGANChanging(global::System.String value);
        partial void OnPERSON_DOCUMENT_ORGANChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SEX_NAME
        {
            get
            {
                return _SEX_NAME;
            }
            set
            {
                OnSEX_NAMEChanging(value);
                ReportPropertyChanging("SEX_NAME");
                _SEX_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SEX_NAME");
                OnSEX_NAMEChanged();
            }
        }
        private global::System.String _SEX_NAME;
        partial void OnSEX_NAMEChanging(global::System.String value);
        partial void OnSEX_NAMEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String POSTAL_CODE
        {
            get
            {
                return _POSTAL_CODE;
            }
            set
            {
                OnPOSTAL_CODEChanging(value);
                ReportPropertyChanging("POSTAL_CODE");
                _POSTAL_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("POSTAL_CODE");
                OnPOSTAL_CODEChanged();
            }
        }
        private global::System.String _POSTAL_CODE;
        partial void OnPOSTAL_CODEChanging(global::System.String value);
        partial void OnPOSTAL_CODEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String E_MAIL
        {
            get
            {
                return _E_MAIL;
            }
            set
            {
                OnE_MAILChanging(value);
                ReportPropertyChanging("E_MAIL");
                _E_MAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("E_MAIL");
                OnE_MAILChanged();
            }
        }
        private global::System.String _E_MAIL;
        partial void OnE_MAILChanging(global::System.String value);
        partial void OnE_MAILChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PHONE
        {
            get
            {
                return _PHONE;
            }
            set
            {
                OnPHONEChanging(value);
                ReportPropertyChanging("PHONE");
                _PHONE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PHONE");
                OnPHONEChanged();
            }
        }
        private global::System.String _PHONE;
        partial void OnPHONEChanging(global::System.String value);
        partial void OnPHONEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADDRESS_OF_LOCATION
        {
            get
            {
                return _ADDRESS_OF_LOCATION;
            }
            set
            {
                OnADDRESS_OF_LOCATIONChanging(value);
                ReportPropertyChanging("ADDRESS_OF_LOCATION");
                _ADDRESS_OF_LOCATION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADDRESS_OF_LOCATION");
                OnADDRESS_OF_LOCATIONChanged();
            }
        }
        private global::System.String _ADDRESS_OF_LOCATION;
        partial void OnADDRESS_OF_LOCATIONChanging(global::System.String value);
        partial void OnADDRESS_OF_LOCATIONChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HOSTEL
        {
            get
            {
                return _HOSTEL;
            }
            set
            {
                OnHOSTELChanging(value);
                ReportPropertyChanging("HOSTEL");
                _HOSTEL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HOSTEL");
                OnHOSTELChanged();
            }
        }
        private Nullable<global::System.Int32> _HOSTEL;
        partial void OnHOSTELChanging(Nullable<global::System.Int32> value);
        partial void OnHOSTELChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ROOM_HOSTEL
        {
            get
            {
                return _ROOM_HOSTEL;
            }
            set
            {
                OnROOM_HOSTELChanging(value);
                ReportPropertyChanging("ROOM_HOSTEL");
                _ROOM_HOSTEL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ROOM_HOSTEL");
                OnROOM_HOSTELChanged();
            }
        }
        private global::System.String _ROOM_HOSTEL;
        partial void OnROOM_HOSTELChanging(global::System.String value);
        partial void OnROOM_HOSTELChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADOPTED_DOC_NUMBER
        {
            get
            {
                return _ADOPTED_DOC_NUMBER;
            }
            set
            {
                OnADOPTED_DOC_NUMBERChanging(value);
                ReportPropertyChanging("ADOPTED_DOC_NUMBER");
                _ADOPTED_DOC_NUMBER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADOPTED_DOC_NUMBER");
                OnADOPTED_DOC_NUMBERChanged();
            }
        }
        private global::System.String _ADOPTED_DOC_NUMBER;
        partial void OnADOPTED_DOC_NUMBERChanging(global::System.String value);
        partial void OnADOPTED_DOC_NUMBERChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ADOPTED_DOC_DATE
        {
            get
            {
                return _ADOPTED_DOC_DATE;
            }
            set
            {
                OnADOPTED_DOC_DATEChanging(value);
                ReportPropertyChanging("ADOPTED_DOC_DATE");
                _ADOPTED_DOC_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ADOPTED_DOC_DATE");
                OnADOPTED_DOC_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _ADOPTED_DOC_DATE;
        partial void OnADOPTED_DOC_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnADOPTED_DOC_DATEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ENTRY_DATE
        {
            get
            {
                return _ENTRY_DATE;
            }
            set
            {
                OnENTRY_DATEChanging(value);
                ReportPropertyChanging("ENTRY_DATE");
                _ENTRY_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ENTRY_DATE");
                OnENTRY_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _ENTRY_DATE;
        partial void OnENTRY_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnENTRY_DATEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FACULTY_LONG_NAME
        {
            get
            {
                return _FACULTY_LONG_NAME;
            }
            set
            {
                OnFACULTY_LONG_NAMEChanging(value);
                ReportPropertyChanging("FACULTY_LONG_NAME");
                _FACULTY_LONG_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FACULTY_LONG_NAME");
                OnFACULTY_LONG_NAMEChanged();
            }
        }
        private global::System.String _FACULTY_LONG_NAME;
        partial void OnFACULTY_LONG_NAMEChanging(global::System.String value);
        partial void OnFACULTY_LONG_NAMEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String STUDY_GROUP_NAME
        {
            get
            {
                return _STUDY_GROUP_NAME;
            }
            set
            {
                OnSTUDY_GROUP_NAMEChanging(value);
                ReportPropertyChanging("STUDY_GROUP_NAME");
                _STUDY_GROUP_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("STUDY_GROUP_NAME");
                OnSTUDY_GROUP_NAMEChanged();
            }
        }
        private global::System.String _STUDY_GROUP_NAME;
        partial void OnSTUDY_GROUP_NAMEChanging(global::System.String value);
        partial void OnSTUDY_GROUP_NAMEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STAN
        {
            get
            {
                return _STAN;
            }
            set
            {
                OnSTANChanging(value);
                ReportPropertyChanging("STAN");
                _STAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STAN");
                OnSTANChanged();
            }
        }
        private global::System.String _STAN;
        partial void OnSTANChanging(global::System.String value);
        partial void OnSTANChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATA_STANY
        {
            get
            {
                return _DATA_STANY;
            }
            set
            {
                OnDATA_STANYChanging(value);
                ReportPropertyChanging("DATA_STANY");
                _DATA_STANY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATA_STANY");
                OnDATA_STANYChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATA_STANY;
        partial void OnDATA_STANYChanging(Nullable<global::System.DateTime> value);
        partial void OnDATA_STANYChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAKAZ_STANY
        {
            get
            {
                return _NAKAZ_STANY;
            }
            set
            {
                OnNAKAZ_STANYChanging(value);
                ReportPropertyChanging("NAKAZ_STANY");
                _NAKAZ_STANY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAKAZ_STANY");
                OnNAKAZ_STANYChanged();
            }
        }
        private global::System.String _NAKAZ_STANY;
        partial void OnNAKAZ_STANYChanging(global::System.String value);
        partial void OnNAKAZ_STANYChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SERIYA_ZALIK
        {
            get
            {
                return _SERIYA_ZALIK;
            }
            set
            {
                OnSERIYA_ZALIKChanging(value);
                ReportPropertyChanging("SERIYA_ZALIK");
                _SERIYA_ZALIK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SERIYA_ZALIK");
                OnSERIYA_ZALIKChanged();
            }
        }
        private global::System.String _SERIYA_ZALIK;
        partial void OnSERIYA_ZALIKChanging(global::System.String value);
        partial void OnSERIYA_ZALIKChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOMER_ZALIK
        {
            get
            {
                return _NOMER_ZALIK;
            }
            set
            {
                OnNOMER_ZALIKChanging(value);
                ReportPropertyChanging("NOMER_ZALIK");
                _NOMER_ZALIK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOMER_ZALIK");
                OnNOMER_ZALIKChanged();
            }
        }
        private global::System.String _NOMER_ZALIK;
        partial void OnNOMER_ZALIKChanging(global::System.String value);
        partial void OnNOMER_ZALIKChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATA_ZALIK
        {
            get
            {
                return _DATA_ZALIK;
            }
            set
            {
                OnDATA_ZALIKChanging(value);
                ReportPropertyChanging("DATA_ZALIK");
                _DATA_ZALIK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATA_ZALIK");
                OnDATA_ZALIKChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATA_ZALIK;
        partial void OnDATA_ZALIKChanging(Nullable<global::System.DateTime> value);
        partial void OnDATA_ZALIKChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 COURSE_ID
        {
            get
            {
                return _COURSE_ID;
            }
            set
            {
                OnCOURSE_IDChanging(value);
                ReportPropertyChanging("COURSE_ID");
                _COURSE_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("COURSE_ID");
                OnCOURSE_IDChanged();
            }
        }
        private global::System.Int32 _COURSE_ID;
        partial void OnCOURSE_IDChanging(global::System.Int32 value);
        partial void OnCOURSE_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IS_CONTRACT
        {
            get
            {
                return _IS_CONTRACT;
            }
            set
            {
                OnIS_CONTRACTChanging(value);
                ReportPropertyChanging("IS_CONTRACT");
                _IS_CONTRACT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IS_CONTRACT");
                OnIS_CONTRACTChanged();
            }
        }
        private global::System.String _IS_CONTRACT;
        partial void OnIS_CONTRACTChanging(global::System.String value);
        partial void OnIS_CONTRACTChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FORMA
        {
            get
            {
                return _FORMA;
            }
            set
            {
                OnFORMAChanging(value);
                ReportPropertyChanging("FORMA");
                _FORMA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FORMA");
                OnFORMAChanged();
            }
        }
        private global::System.String _FORMA;
        partial void OnFORMAChanging(global::System.String value);
        partial void OnFORMAChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OSVITA_LEVEL_ID
        {
            get
            {
                return _OSVITA_LEVEL_ID;
            }
            set
            {
                OnOSVITA_LEVEL_IDChanging(value);
                ReportPropertyChanging("OSVITA_LEVEL_ID");
                _OSVITA_LEVEL_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OSVITA_LEVEL_ID");
                OnOSVITA_LEVEL_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _OSVITA_LEVEL_ID;
        partial void OnOSVITA_LEVEL_IDChanging(Nullable<global::System.Int32> value);
        partial void OnOSVITA_LEVEL_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SPECIALITY_CODE
        {
            get
            {
                return _SPECIALITY_CODE;
            }
            set
            {
                OnSPECIALITY_CODEChanging(value);
                ReportPropertyChanging("SPECIALITY_CODE");
                _SPECIALITY_CODE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SPECIALITY_CODE");
                OnSPECIALITY_CODEChanged();
            }
        }
        private global::System.String _SPECIALITY_CODE;
        partial void OnSPECIALITY_CODEChanging(global::System.String value);
        partial void OnSPECIALITY_CODEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SPECIALITY_NAME
        {
            get
            {
                return _SPECIALITY_NAME;
            }
            set
            {
                OnSPECIALITY_NAMEChanging(value);
                ReportPropertyChanging("SPECIALITY_NAME");
                _SPECIALITY_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SPECIALITY_NAME");
                OnSPECIALITY_NAMEChanged();
            }
        }
        private global::System.String _SPECIALITY_NAME;
        partial void OnSPECIALITY_NAMEChanging(global::System.String value);
        partial void OnSPECIALITY_NAMEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SPECIALIZATION_ID
        {
            get
            {
                return _SPECIALIZATION_ID;
            }
            set
            {
                OnSPECIALIZATION_IDChanging(value);
                ReportPropertyChanging("SPECIALIZATION_ID");
                _SPECIALIZATION_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SPECIALIZATION_ID");
                OnSPECIALIZATION_IDChanged();
            }
        }
        private global::System.String _SPECIALIZATION_ID;
        partial void OnSPECIALIZATION_IDChanging(global::System.String value);
        partial void OnSPECIALIZATION_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRIVILEG_NAME
        {
            get
            {
                return _PRIVILEG_NAME;
            }
            set
            {
                OnPRIVILEG_NAMEChanging(value);
                ReportPropertyChanging("PRIVILEG_NAME");
                _PRIVILEG_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRIVILEG_NAME");
                OnPRIVILEG_NAMEChanged();
            }
        }
        private global::System.String _PRIVILEG_NAME;
        partial void OnPRIVILEG_NAMEChanging(global::System.String value);
        partial void OnPRIVILEG_NAMEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRIVILEG_SERIES
        {
            get
            {
                return _PRIVILEG_SERIES;
            }
            set
            {
                OnPRIVILEG_SERIESChanging(value);
                ReportPropertyChanging("PRIVILEG_SERIES");
                _PRIVILEG_SERIES = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRIVILEG_SERIES");
                OnPRIVILEG_SERIESChanged();
            }
        }
        private global::System.String _PRIVILEG_SERIES;
        partial void OnPRIVILEG_SERIESChanging(global::System.String value);
        partial void OnPRIVILEG_SERIESChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRIVILEG_NUMBER
        {
            get
            {
                return _PRIVILEG_NUMBER;
            }
            set
            {
                OnPRIVILEG_NUMBERChanging(value);
                ReportPropertyChanging("PRIVILEG_NUMBER");
                _PRIVILEG_NUMBER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRIVILEG_NUMBER");
                OnPRIVILEG_NUMBERChanged();
            }
        }
        private global::System.String _PRIVILEG_NUMBER;
        partial void OnPRIVILEG_NUMBERChanging(global::System.String value);
        partial void OnPRIVILEG_NUMBERChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PRIVILEG_DATE
        {
            get
            {
                return _PRIVILEG_DATE;
            }
            set
            {
                OnPRIVILEG_DATEChanging(value);
                ReportPropertyChanging("PRIVILEG_DATE");
                _PRIVILEG_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRIVILEG_DATE");
                OnPRIVILEG_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _PRIVILEG_DATE;
        partial void OnPRIVILEG_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnPRIVILEG_DATEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GRADUATED_DATE
        {
            get
            {
                return _GRADUATED_DATE;
            }
            set
            {
                OnGRADUATED_DATEChanging(value);
                ReportPropertyChanging("GRADUATED_DATE");
                _GRADUATED_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GRADUATED_DATE");
                OnGRADUATED_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _GRADUATED_DATE;
        partial void OnGRADUATED_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnGRADUATED_DATEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserAccountId
        {
            get
            {
                return _UserAccountId;
            }
            set
            {
                OnUserAccountIdChanging(value);
                ReportPropertyChanging("UserAccountId");
                _UserAccountId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserAccountId");
                OnUserAccountIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserAccountId;
        partial void OnUserAccountIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserAccountIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LOGIN_CHANGE_DATE
        {
            get
            {
                return _LOGIN_CHANGE_DATE;
            }
            set
            {
                OnLOGIN_CHANGE_DATEChanging(value);
                ReportPropertyChanging("LOGIN_CHANGE_DATE");
                _LOGIN_CHANGE_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LOGIN_CHANGE_DATE");
                OnLOGIN_CHANGE_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _LOGIN_CHANGE_DATE;
        partial void OnLOGIN_CHANGE_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnLOGIN_CHANGE_DATEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RtStudyGroupId
        {
            get
            {
                return _RtStudyGroupId;
            }
            set
            {
                OnRtStudyGroupIdChanging(value);
                ReportPropertyChanging("RtStudyGroupId");
                _RtStudyGroupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RtStudyGroupId");
                OnRtStudyGroupIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RtStudyGroupId;
        partial void OnRtStudyGroupIdChanging(Nullable<global::System.Int32> value);
        partial void OnRtStudyGroupIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> vcChangeDate
        {
            get
            {
                return _vcChangeDate;
            }
            set
            {
                OnvcChangeDateChanging(value);
                ReportPropertyChanging("vcChangeDate");
                _vcChangeDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vcChangeDate");
                OnvcChangeDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _vcChangeDate;
        partial void OnvcChangeDateChanging(Nullable<global::System.DateTime> value);
        partial void OnvcChangeDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vcChangeStatus
        {
            get
            {
                return _vcChangeStatus;
            }
            set
            {
                OnvcChangeStatusChanging(value);
                ReportPropertyChanging("vcChangeStatus");
                _vcChangeStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vcChangeStatus");
                OnvcChangeStatusChanged();
            }
        }
        private global::System.String _vcChangeStatus;
        partial void OnvcChangeStatusChanging(global::System.String value);
        partial void OnvcChangeStatusChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modeltest", "UserAccountsPersonality", "UserAccount")]
        public UserAccount UserAccount
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserAccount>("Modeltest.UserAccountsPersonality", "UserAccount").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserAccount>("Modeltest.UserAccountsPersonality", "UserAccount").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserAccount> UserAccountReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserAccount>("Modeltest.UserAccountsPersonality", "UserAccount");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserAccount>("Modeltest.UserAccountsPersonality", "UserAccount", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modeltest", Name="UserAccount")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserAccount : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта UserAccount.
        /// </summary>
        /// <param name="userAccountId">Исходное значение свойства UserAccountId.</param>
        /// <param name="login">Исходное значение свойства Login.</param>
        /// <param name="password">Исходное значение свойства Password.</param>
        public static UserAccount CreateUserAccount(global::System.Int32 userAccountId, global::System.String login, global::System.String password)
        {
            UserAccount userAccount = new UserAccount();
            userAccount.UserAccountId = userAccountId;
            userAccount.Login = login;
            userAccount.Password = password;
            return userAccount;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserAccountId
        {
            get
            {
                return _UserAccountId;
            }
            set
            {
                if (_UserAccountId != value)
                {
                    OnUserAccountIdChanging(value);
                    ReportPropertyChanging("UserAccountId");
                    _UserAccountId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserAccountId");
                    OnUserAccountIdChanged();
                }
            }
        }
        private global::System.Int32 _UserAccountId;
        partial void OnUserAccountIdChanging(global::System.Int32 value);
        partial void OnUserAccountIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewPassword
        {
            get
            {
                return _NewPassword;
            }
            set
            {
                OnNewPasswordChanging(value);
                ReportPropertyChanging("NewPassword");
                _NewPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NewPassword");
                OnNewPasswordChanged();
            }
        }
        private global::System.String _NewPassword;
        partial void OnNewPasswordChanging(global::System.String value);
        partial void OnNewPasswordChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cookie
        {
            get
            {
                return _Cookie;
            }
            set
            {
                OnCookieChanging(value);
                ReportPropertyChanging("Cookie");
                _Cookie = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cookie");
                OnCookieChanged();
            }
        }
        private global::System.String _Cookie;
        partial void OnCookieChanging(global::System.String value);
        partial void OnCookieChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ScientificInterest
        {
            get
            {
                return _ScientificInterest;
            }
            set
            {
                OnScientificInterestChanging(value);
                ReportPropertyChanging("ScientificInterest");
                _ScientificInterest = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ScientificInterest");
                OnScientificInterestChanged();
            }
        }
        private global::System.String _ScientificInterest;
        partial void OnScientificInterestChanging(global::System.String value);
        partial void OnScientificInterestChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodeAssembly
        {
            get
            {
                return _CodeAssembly;
            }
            set
            {
                OnCodeAssemblyChanging(value);
                ReportPropertyChanging("CodeAssembly");
                _CodeAssembly = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodeAssembly");
                OnCodeAssemblyChanged();
            }
        }
        private global::System.String _CodeAssembly;
        partial void OnCodeAssemblyChanging(global::System.String value);
        partial void OnCodeAssemblyChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modeltest", "UserAccountsPersonality", "sPersonality")]
        public EntityCollection<sPersonality> sPersonality
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<sPersonality>("Modeltest.UserAccountsPersonality", "sPersonality");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<sPersonality>("Modeltest.UserAccountsPersonality", "sPersonality", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
